const adminRepository = require('../repositories/adminRepository');
const AppError = require('../utils/AppError');
const { formatDateLabel } = require('../utils/dateTime');
const { bookingStatusMeta, paymentStatusMeta, toDateInput } = require('../utils/booking');
const { getPitchImage, pitchStatusMeta, PITCH_TYPES } = require('../utils/pitch');
const {
  ACCOUNT_ROLES, ACCOUNT_STATUSES, BOOKING_STATUSES, PAYMENT_STATUSES, PITCH_STATUSES,
  normalizeAreaId, normalizeChoice, normalizePage, normalizeText, requireAdmin, roleLabel, statusMeta,
  validateAccountStatus, validateAreaInput,
} = require('../utils/admin');

const PAGE_SIZE = 12;
function pagination(page,total){return {page,pageSize:PAGE_SIZE,totalItems:total,totalPages:Math.max(1,Math.ceil(total/PAGE_SIZE))};}
function moneyRow(row, fields=['tong_tien']) { const copy={...row}; fields.forEach((f)=>{ if(f in copy) copy[f]=Number(copy[f]||0); }); return copy; }
function mapAccount(row,currentUser){return {...row,roleLabel:roleLabel(row.vai_tro),statusMeta:statusMeta(row.trang_thai),canChangeStatus:row.vai_tro!=='Admin'&&row.ma_tai_khoan!==currentUser.accountId};}
function mapBooking(row){const date=toDateInput(row.ngay_dat);const bs=bookingStatusMeta(row.trang_thai_dat);const ps=paymentStatusMeta(row.trang_thai_thanh_toan);return {...moneyRow(row,['tien_san','tong_tien_san','tong_tien_dich_vu','tong_tien']),ngay_dat:date,ngay_dat_label:formatDateLabel(date),timeLabel:`${row.gio_bat_dau} - ${row.gio_ket_thuc}`,bookingStatus:{...bs,tone:bs.key==='confirmed'?'success':bs.key==='pending'?'warning':'danger'},paymentStatus:{...ps,tone:ps.key==='paid'?'success':'warning'}};}
function mapInvoice(row){const date=toDateInput(row.ngay_dat);const ps=paymentStatusMeta(row.trang_thai_thanh_toan);return {...moneyRow(row,['tong_tien_san','tong_tien_dich_vu','tong_tien']),ngay_dat:date,ngay_dat_label:formatDateLabel(date),paymentStatus:{...ps,tone:ps.key==='paid'?'success':'warning'}};}
function mapPitch(row){const meta=pitchStatusMeta(row.trang_thai);return {...row,gia_thue:Number(row.gia_thue||0),so_luot_dat:Number(row.so_luot_dat||0),imageUrl:getPitchImage(row.loai_san,row.image_url),statusMeta:{...meta,tone:row.trang_thai==='Hoat dong'?'success':row.trang_thai==='Bao tri'?'warning':'muted'}};}
function mapError(error){if(error.code==='ACCOUNT_NOT_FOUND'||error.code==='AREA_NOT_FOUND')return new AppError(error.message,404,error.code);if(error.code==='AREA_IN_USE')return new AppError(error.message,409,error.code);if(error.code==='23505')return new AppError('Dữ liệu bị trùng với bản ghi hiện có.',409,'DUPLICATE_DATA');return error;}

module.exports={
 async getStatus(){return adminRepository.healthCheck();},
 async getDashboard(user){requireAdmin(user);const d=await adminRepository.getDashboard();const roleCounts=Object.fromEntries(ACCOUNT_ROLES.map(r=>[r,0]));d.accountRoles.forEach(r=>{roleCounts[r.vai_tro]=Number(r.so_luong||0);});return {stats:{totalAccounts:Number(d.stats.tong_tai_khoan||0),lockedAccounts:Number(d.stats.tai_khoan_bi_khoa||0),totalPitches:Number(d.stats.tong_san||0),activePitches:Number(d.stats.san_hoat_dong||0),totalBookings:Number(d.stats.tong_don||0),pendingBookings:Number(d.stats.don_cho_xac_nhan||0),unpaidInvoices:Number(d.stats.hoa_don_chua_thanh_toan||0),paidRevenue:Number(d.stats.tong_doanh_thu||0)},roleCounts,recentBookings:d.recentBookings.map(mapBooking),recentPayments:d.recentPayments.map(mapInvoice)};},
 async getAccounts(query,user){requireAdmin(user);const page=normalizePage(query.page);const q=normalizeText(query.q,80);const role=normalizeChoice(query.role,ACCOUNT_ROLES);const status=normalizeChoice(query.status,ACCOUNT_STATUSES);const result=await adminRepository.findAccounts({q,role,status,limit:PAGE_SIZE,offset:(page-1)*PAGE_SIZE});const p=pagination(page,result.total);if(page>p.totalPages&&result.total)return this.getAccounts({...query,page:p.totalPages},user);return {accounts:result.rows.map(r=>mapAccount(r,user)),filters:{q,role,status},roles:ACCOUNT_ROLES.map(v=>({value:v,label:roleLabel(v)})),statuses:ACCOUNT_STATUSES,pagination:p};},
 async setAccountStatus(accountId,rawStatus,user){requireAdmin(user);const id=normalizeText(accountId,20);if(id===user.accountId)throw new AppError('Bạn không thể khóa chính tài khoản quản trị đang đăng nhập.',409,'CANNOT_LOCK_SELF');const status=validateAccountStatus(rawStatus);try{const existing=await adminRepository.findAccountById(id);if(existing?.vai_tro==='Admin')throw new AppError('Không thay đổi trạng thái tài khoản quản trị viên từ màn hình này.',403,'ADMIN_STATUS_PROTECTED');return mapAccount(await adminRepository.updateAccountStatus({accountId:id,status}),user);}catch(e){throw mapError(e);}},
 async getAreas(user){requireAdmin(user);return {areas:(await adminRepository.findAreas()).map(r=>({...r,so_san:Number(r.so_san||0),so_luot_dat:Number(r.so_luot_dat||0)}))};},
 async createArea(payload,user){requireAdmin(user);try{return await adminRepository.createArea(validateAreaInput(payload));}catch(e){throw mapError(e);}},
 async updateArea(areaId,payload,user){requireAdmin(user);try{const area=await adminRepository.updateArea({areaId:normalizeAreaId(areaId),...validateAreaInput(payload)});if(!area)throw Object.assign(new Error('Không tìm thấy khu vực.'),{code:'AREA_NOT_FOUND'});return area;}catch(e){throw mapError(e);}},
 async deleteArea(areaId,user){requireAdmin(user);try{return await adminRepository.deleteArea(normalizeAreaId(areaId));}catch(e){throw mapError(e);}},
 async getPitches(query,user){requireAdmin(user);const page=normalizePage(query.page);const q=normalizeText(query.q,80);const status=normalizeChoice(query.status,PITCH_STATUSES);const type=normalizeChoice(query.type,PITCH_TYPES);const r=await adminRepository.findPitches({q,status,type,limit:PAGE_SIZE,offset:(page-1)*PAGE_SIZE});return {pitches:r.rows.map(mapPitch),filters:{q,status,type},statuses:PITCH_STATUSES,pitchTypes:PITCH_TYPES,pagination:pagination(page,r.total)};},
 async getBookings(query,user){requireAdmin(user);const page=normalizePage(query.page);const q=normalizeText(query.q,80);const bookingStatus=normalizeChoice(query.bookingStatus,BOOKING_STATUSES);const paymentStatus=normalizeChoice(query.paymentStatus,PAYMENT_STATUSES);const r=await adminRepository.findBookings({q,bookingStatus,paymentStatus,limit:PAGE_SIZE,offset:(page-1)*PAGE_SIZE});return {bookings:r.rows.map(mapBooking),filters:{q,bookingStatus,paymentStatus},bookingStatuses:BOOKING_STATUSES,paymentStatuses:PAYMENT_STATUSES,pagination:pagination(page,r.total)};},
 async getInvoices(query,user){requireAdmin(user);const page=normalizePage(query.page);const status=normalizeChoice(query.status,PAYMENT_STATUSES);const r=await adminRepository.findInvoices({status,limit:PAGE_SIZE,offset:(page-1)*PAGE_SIZE});return {invoices:r.rows.map(mapInvoice),filters:{status},paymentStatuses:PAYMENT_STATUSES,pagination:pagination(page,r.total)};},
 async getStatistics(user){requireAdmin(user);const d=await adminRepository.getStatistics();const segmentCounts={VIP:0,'Than thiet':0,'Tiem nang':0};d.customerSegments.forEach(r=>{segmentCounts[r.phan_loai]=(segmentCounts[r.phan_loai]||0)+1;});return {topCustomers:d.topCustomers.map(r=>({...r,tong_chi_tieu:Number(r.tong_chi_tieu||0)})),segmentCounts,monthly:d.monthly.map(r=>({...moneyRow(r,['doanh_thu_tien_san','doanh_thu_dich_vu','tong_doanh_thu']),thang:toDateInput(r.thang)})),areas:d.areas.map(r=>moneyRow(r,['doanh_thu_tien_san','doanh_thu_dich_vu','tong_doanh_thu'])),pitches:d.pitches.map(r=>moneyRow(r,['doanh_thu_tien_san','doanh_thu_dich_vu','tong_doanh_thu'])),services:d.services.map(r=>moneyRow(r,['doanh_thu_dich_vu'])),cancellation:{total:Number(d.cancellation.tong_so_don||0),cancelled:Number(d.cancellation.so_don_huy||0),rate:Number(d.cancellation.ty_le_huy_phan_tram||0)}};},
 _private:{mapAccount,mapBooking,mapInvoice,mapPitch,pagination,validateAreaInput,normalizeChoice,requireAdmin}
};
